### ISSUE TITLE
visual studio missing 1 file

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [adplug/adplug#116]
hi

When trying to compile using the visual studio file on github, there is 1 file missing version.h
Can somebody add this file because it can't be compiled without this file

thx

**Comment by jessicajonesunitedkingdom** [comment]
I renamed the file "version.h.in" to "version.h" and it seems to work now (It compiles, not sure if correctly working).
Why is "version.h.in" used instead of "version.h" on github?

Using visual studio solution file of github, I see the result is a library file "adplug.lib". This is compiled successfully.

- Can somebody tell me how I can compile a DLL instead of a LIB file for using in another application?

- is this possible by using the visual studio solution file of github and if yes, how to do it (what settings to change or are there code changes to adplug files needed too)?

Thx in advance!

**Comment by zeromus** [comment]
You do not "using in another application" without adding additional code to adplug to make it work in that application. If you can do that, then you know how to compile this as a dll. If someone else can do that, then they know how to compile it as a dll. The HippoPlayer developer knows how to do that. You should be asking him for help.

**Comment by jessicajonesunitedkingdom** [comment]
hi

Do you know how to compile a DLL using visual studio and do you want to explain how it works?
You tell I need to add code to adplug.
I'm no adplug developer and don't know anything about the internal workings of adplug.

- Can you attach the changed source code files of adplug here I need to compile a DLL ?

- I also don't know if I need to do additional settings in visual studio to compile a DLL. Do you know?

ps: the developer of hippoplayer does not use visual studio and can't help me with this specific compiler

thx in advance!

**Comment by zeromus** [comment]
Ordinarily you would build a plugin for hippoplayer in the same way the developer of hippoplayer builds the plugins for hippoplayer. That means using his code and his tools. You aren't giving us any useful information to work with. If I tell you how to build a DLL, you're still not going to get what you're looking for (whatever that is) and you're just going to be back here again, and again, asking questions that don't really have anything to do with adplug but rather involve basic software development and whatever application you're trying to extend.  You could ask google "how to build solution as dll" and get an answer but it won't actually get you what you need.

**Comment by mywave82** [comment]
On linux, bsd, mingw and msys2 systems, we execute the configure shell script in our terminal/console, which checks our systems for compatibility etc, and it uses the .in files as templates for generating various project files, replacing all the @VAR@ things with the results. In visual studio, you would need to ensure that depencies etc is installed and manually create the version.h files an similiar. Alternative build systems for windows developers exists, but might not be implemented in adplug. Patches is welcome if that is the case (I use this project in Linux which compiles as-is)

**Comment by jessicajonesunitedkingdom** [comment]
Hi zeromus,

I asked hippoplayer developer but he tells me this:

- he says the opposite of you: NO additional code is needed to compile a DLL

- he has NO knowledge in doing this using visual studio

See: https://github.com/emoon/HippoPlayer/issues/90

I want to ask one last time if YOU want to explain me how to do it?

I just want to compile a DLL file of adplug: i'm not making a hippoplayer plugin, just a simple DLL file which can be used in another C++ (or C#) program.
So i'm not wanting to make a plugin for hippoplayer, not for any other player.
I just want to compile a DLL file which can be used to play adplug supported formats in another application, by using this DLL file I compiled myself.

If you can/want to help, please tell me how this can be done.

Until now, I successfully compiled a .LIB file using visual studio. But I want a DLL instead.

My questions are:

- if you say I need additional code: can you please tell me where and what code? 

- Is it possible to attach the changed source code files that I need to compile my DLL?

I did not find the way of doing this in google. 

thx in advance!

**Comment by zeromus** [comment]
No additional code is needed to compile a dll THAT DOES NOTHING. Additional code is required to make a dll that does anything.

To make a dll THAT DOES NOTHING, edit adplug.vcxproj and replace StaticLibrary with DynamicLibrary.

To make the dll DO SOMETHING, ask a general windows programming support forum, because your questions have nothing to do with adplug. But keep up your diligent spirit! In a few months you will have made it far enough as having a question having something to do with adplug.

**Comment by mywave82** [comment]
https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019

**Comment by jessicajonesunitedkingdom** [comment]
According to this: https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019

you NEED additional code in the adplug code to COMPILE it...
So the adplug developer is right.

So you don't do those things here?

#ifdef MATHLIBRARY_EXPORTS
#define MATHLIBRARY_API __declspec(dllexport)
#else
#define MATHLIBRARY_API __declspec(dllimport)
#endif

or for a method:

extern "C" MATHLIBRARY_API void fibonacci_init(
    const unsigned long long a, const unsigned long long b);

You don't do this?
How can you compile your DLL without saying which methods the DLL provides by using "extern"?
Since you use visual studio compîler too, I assume you have to do this too?

Does ANYBODY really knows what you are talking about?
I'm afraid not, since after 3 days I still don't get an answer.

My question is very CLEAR:

what methods of adplug and in which source code file(s) of adplug must be declared like above here?
With the extern "C" code...

Thanks

**Comment by jessicajonesunitedkingdom** [comment]
So this IS a question about adplug because I ask WHAT methods of ADPLUG I need to declare using "extern" to be able to play files in another application using this DLL.

So don't tell me to go to another forum...
And also give another answer I can't do anything about it, zeromus

**Comment by zeromus** [comment]
I think you only need those declspecs when building with visual studio. Music player dev doesn't build with visual studio.
Since you're building with visual studio you certainly need them. Which methods -- whichever one you need in MATHAPPLICATION, of course. Figuring this out is the hard part. 
I'm not sure who "you" is referring to. It seems like you're asking this person how it is they don't need declspecs, but then say "since you use visual studio compiler" when you know certainly by now he does not use visual studio.

**Comment by jessicajonesunitedkingdom** [comment]
zeromus, here some facts:

1) this is my last message: **WHAT METHODS TO DECLARE USING 'EXTERN**'?
Do you know this? Yes or no? If yes, answer. If no, don't answer anything I can't use

2) hippoplayer developer DOES use visual studio but not the IDE itself.
He calls the compiler by using the command line but does NOT use the visual studio projects.

3) since 2) is true, he still tells he DOES NOT use "extern" or any other code change in adplug to compile his DLL

Since 2) and 3) are true according to hippoplayer developer, this is impossible according to me...

We both use visual studio, there can't be some magic thing happening which causes the DLL to compile on his pc without extra code but not on mine...

**Comment by zeromus** [comment]
I am reluctant to tell you any more since you have very, very, very, very bad manners and giving you help may reward you and teach you to continue behaving badly. And in fact you're not going to get any more out of me without acknowledging that your manners are terrible even if you don't understand why. There is no sense even explaining why until you agree that there's anything for me to explain. On the other hand if I give you all the answers, you may go away and stop making noise. What a conundrum.

HippoPlayer exports only hippo_playback_plugin() from adplug_plugin.cpp
see it marked as HIPPO_EXPORT? That's `__declspec(dllexport)` (see it in line 331 of HippoPlugin.h)
I suggest you add his adplug_plugin.cpp (in other words, "additional code to compile a dll that does anything")
And then you only need the one function exported to c#.
But, on the c# side you will no doubt find it to be easier if you dllexport each of the functions in g_adplug_plugin. As you work through it you will find out that `hippo_playback_plugin` is just an annoyance.

**Comment by jessicajonesunitedkingdom** [comment]
I don't want to use hippoplayer shit you fuxking retard
You keep telling thensame thing.
do you even read what i'say?

**Comment by jessicajonesunitedkingdom** [comment]
SUXK MY FUCKING CLIT

**Comment by zeromus** [comment]
Hippoplayer is a program that uses adplug.
Your program is a program that uses adplug.
Whatever hippoplayer exports is probably what you need.
If you export whatever hippoplayer exports, you will probably export whatever you need.
If you copy the file hippoplayer uses to do its exports, you probably won't have to write any new c++ code at all.

**Comment by jessicajonesunitedkingdom** [comment]
SUCK MY CLIT EVEN HARDER SISSY BOY

**Comment by jessicajonesunitedkingdom** [comment]
adplug can suck'?y clit too

stupid library without dll
it's useless written by'linux faggots

**Comment by jessicajonesunitedkingdom** [comment]
fuck a hippo faggot

**Comment by jessicajonesunitedkingdom** [comment]
ok thank you very much for the help!!!
