### ISSUE TITLE
ALLOYRUN.RAD sounds terrible when surround enabled

### ISSUE THREAD

**Issue by HunterZ** [adplug/adplug#120]
I cloned the latest adplug + adplay-linux sources from here on GitHub, built adplug in VS2017, then hacked up adplay-linux to compile just the disk output + generate some visuals for ffmpeg to encode in real-time.

For some reason ALLOYRUN.RAD sounds absolutely awful. I tried downloading an official copy, but the md5sum was the same as the one included with adplug as a test song.

Below is a link to the video rendered using the Nuked emulator (16-bit, 49716Hz, surround enabled). I also tried Woody and it also sounds just as bad.

Any idea what's gone wrong here?

https://twitter.com/HunterZ0/status/1317216660743364608

**Comment by HunterZ** [comment]
Update:

I tried reverting to the 2.3.3 release but had the same problem.

After trying a few things, I discovered that the surround feature seems to be involved. If I turn it off, the output sounds reasonable with both Nuked and Woody - except that I get no stereo even though AdPlug is configured for stereo instead of mono.

...or maybe I'm only testing with mono songs? Is there a known stereo OPL3 song I can test with?

**Comment by Malvineous** [comment]
@devinacker Is this one you can look at?

**Comment by devinacker** [comment]
Enabling surround seems to give me the same issue regardless of format (i.e. I tried RAD, D00, HSC, etc.) and regardless of emulator, sample rate, etc.

Seems to be an issue with the surround feature itself, rather than any of the individual format players. The symptom (for me, at least) is a loud constant buzzing that only varies with the output sample rate; the waveform suggests that maybe surround output is only ever partially filling out the output buffer?
![image](https://user-images.githubusercontent.com/4616298/96328338-f7a0da80-100f-11eb-98a5-4b6141ff0dd3.png)

**Comment by Malvineous** [comment]
I don't get a buzzing at all (using ALSA output device), but I do get some pops and cracks when listening to some files (e.g. `test/dro_v2.dro`) with NukedOPL in surround (but not with NukedOPL in stereo).  I'm not entirely sure why this is the case but it must be down to a bug in the pitch bending algorithm the surround effect uses, as other files (`test/doofus.dro`) sound fine in stereo and surround.

However listening to `test/ALLOYRUN.RAD` in surround mode with NukedOPL or WoodyOPL does result in the instruments sounding different compared to stereo mode (e.g. the bass line is mostly missing).  The fact that both channels sound wrong when `CSurroundOPL` only changes the register data sent to one synth is a bit odd though.  That suggests that there could be some sort of shared global state between both OPL instances which I don't think is the case.

At any rate the problem seems to be with `CSurroundOPL` rather than the RAD replayer, so if anyone has any ideas what the issue might be there please let us know, or submit a patch if you can fix it!

**Comment by devinacker** [comment]
I messed around a bit more and I don't think `CSurroundopl::write` is the issue, since I noticed the same problems you were describing if I completely remove the writes to the second OPL.

I think it actually might have to do with the changes to `CSurroundopl::update` from 881056dba106b16f6d2e7aca1a15cf4039e781d3, since adplug 2.3.1 doesn't seem to have any issues with surround output.

**Comment by Malvineous** [comment]
Hmm I see there is one bug in that code, the `++offsetR` statement shouldn't be there.  I suppose in theory this could cause the buzzing if the samples didn't line up in the buffer for some reason, but this wouldn't explain why the song is missing notes while having clean output.

**Comment by devinacker** [comment]
Okay, doing some testing with git-bisect and adplay I figured out that the missing notes issue was introduced with the new RAD replayer after all, but 5ca041a seems to have fixed that, at least.

I'll do some more testing later and see if I can figure out what's going on with that strange buffer issue with the Winamp plugin, which is what I was testing with previously.

**Comment by Malvineous** [comment]
Yes, the "issue" in the new RAD replayer was that in `writeOPL()` it relied on `opl->getchip()` working, which it did not in `CSurroundopl`, so it wasn't switching OPL register banks when it needed to.  So fixing CSurroundopl so it worked the same as the other OPL classes solved that.

It's looking like NukedOPL doesn't like odd buffer sizes.  If I change it so that it only generates one or two samples at a time then I get massive audio corruption, but I can't work out why because internally it generates only one sample at a time anyway!  Very odd.

**Comment by devinacker** [comment]
For what it's worth I was having the same buffer problem in Winamp with every emulator, not just NukedOPL.

**Comment by Malvineous** [comment]
Well to further complicate matters, after upgrading NukedOPL to v1.8 now I'm getting the same audio corruption in the normal stereo mode as well.  I haven't looked at the waveform but it looks like I might be seeing the same issue you posted above.

The other emulators are working fine for me, I'm only seeing issues with NukedOPL.

**Comment by Malvineous** [comment]
Ok so it's something up with the audio interface by the looks of it.  If I use the disk writer as the output device then it writes a .wav file that sounds perfect.

**Comment by devinacker** [comment]
ALSA seems to work fine in my Ubuntu VM with various buffer sizes, at least, aside from a usually very short bit of skipping that sometimes happens at the very beginning of playback (which is probably an issue with ALSA or the VM since SDL also works fine)

When I have some time tomorrow I'll start recompiling the Winamp plugin again and see if I can figure out anything on that end.

**Comment by Malvineous** [comment]
I think I've worked out the ALSA problem.  It doesn't do buffering properly, so when some audio has been generated, it plays it, waits for playback to finish, then goes and generates more audio.  This means the emulator has a fraction of a second to generate more samples, and all of them can do it quickly enough except for NukedOPL.  Because it takes just a little bit too long, the handful of samples left in the hardware audio buffer finish playing and the resulting gap causes an audible click.  If the ALSA buffer size is large enough, it actually causes the playback device to go into standby at the end of each buffer flush because it thinks no more audio is arriving, it takes that long to refill the large buffer.

I'm not sure how the Winamp plugin works, but the solution seems to be to start playing the current audio buffer, but generate more samples *while* the buffer is playing - don't wait until the buffer is empty before generating more audio samples.

**Comment by devinacker** [comment]
I figured out what was going on with the Winamp plugin, at least (see adplug/winamp#20).

**Comment by Malvineous** [comment]
Perfect, that's great, thanks for the PR!  With the other fixes as well, I will mark this issue as resolved.

**Comment by binarymaster** [comment]
This problem should be fixed now in Winamp plugin :slightly_smiling_face:
