### ISSUE TITLE
IMF Format Variaton

### ISSUE THREAD

**Issue by thecoreyburton** [adplug/adplug#43]
I came across the demo of Commander Keen's fourth installment and have been trying to play the IMF files that came with it. I thought perhaps I'd extracted them incorrectly and asked for help on several forum pages, only to find that it wasn't an error on my end but rather an apparent bug in ADPlug.

K1n9_Duk3 stated the following: "The demo comes with two songs: SHADOWS.IMF and OASIS.IMF. Both are very different from the final versions used in Keen 4, one noticeable difference being that the songs use the AdLib's rhythm mode. I think Monster Bash is the only other game that ever used IMFs in rhythm mode."

"Extracting the IMFs turned out to be not as easy as one would assume. The AudioT format in the demo differs slightly from the later formats (IMF chunks start with a 4 bytes length value, not 2 bytes like all the later versions). That's why the IMFs in the archive are plain IMF files with no header/footer data. The extracted songs also don't start with zeroes, so some IMF tools might not be able to handle them correctly."

@Malvineous could ADPlug be modified to play these obscure files?

Download of the IMF files: http://home.arcor.de/k1n9duk3/files/k4demo_imfs.zip
Source: http://www.pckf.com/viewtopic.php?p=81805

**Comment by Malvineous** [comment]
I'm not sure modifying AdPlug to pick up these file types would be a good idea.  The reason is that detecting these file formats is notoriously error-prone, so this change would likely result in a whole lot of misdetections of other formats.

Given that there are only two files in this variant, perhaps it is easier to simply insert four 0x00 bytes at the start of the files during the extraction process?  Then the format would match all the other type-0 files out there and nothing would need to be changed.

**Comment by Malvineous** [comment]
Also I just noticed that the IMF files in the .zip have an extra surplus two bytes at the end which are not part of the IMF file and could also be interfering with the autodetection.  If these bytes are treated as part of the song by a player, it will make the song appear to have a massive delay at the end.

**Comment by Malvineous** [comment]
Actually now I'm really confused.  The songs start with note events before they set instruments.  It almost looks like the start of the IMF has been cut off, and the usual lead in where the instruments are programmed is missing!  Are you absolutely sure the files have been extracted correctly?

**Comment by thecoreyburton** [comment]
Thanks @Malvineous, that was a really thorough reply!

So file modification is the best route for now? I'm alright with any outcome that gets them playing in adplug (they're the last ingredient in an adlib-oriented concoction I'm working on). I originally tried adding the bytes at the start to match other IMF files but to no success, is this likely because of being in rhythm-mode?

**Comment by Malvineous** [comment]
I think in this case it would be best.  It would be nice to have them supported, but I think in this case the trade off (mis-identifying lots of unrelated file formats) is not worth the gain for being able to play two files from an obscure version of a game that could be easily fixed with the addition of a couple of extra bytes.  If it was a full commercial release then maybe, but not for a pre-release/demo (in my opinion.)  This is not without precedent - we removed support for pre-release .dro files when the next release of DOSBox came out, and some games (like Duke Nukem II) have been extracted and had their IMF delay byte values doubled in the process so they play at the correct speed.

The appearance of type-0 and type-1 IMF files was already due to a mistake in the extraction process (there is only type-0, the type-1 format accidentally has too much data extracted with it) so I'm reluctant to introduce yet another variant.  Since it's only the addition of the four bytes (plus cleaning off the trailing bytes - not sure about those they seem a bit weird, maybe ask K1n9_Duk3) I think that would far and away be the most reliable solution.

Another alternative would be to extract the four-byte length value and write it as a two-byte value instead, producing a valid type-1 IMF file.

Rhythm mode is specific to the OPL chip and doesn't change the file format in any way.  I have tried to add four 0x00 bytes to the start and this works fine with AdPlug, although autodetection in libgamemusic still fails so there's perhaps more at play here (I think the trailing data is causing problems.  If you cut off the trailing data you are left with half an event at the end of the file though, which doesn't seem right either.)

**Comment by thecoreyburton** [comment]
I definitely agree with you there. Considering the obscurity and fact that (as far as we know) they're the only two IMF files that work this way, it's probably best to keep this a contained case. Given the release date of the "Special Demo" that they were extracted from, it's quite likely they're the very first IMF files created and that could explain the variance in format. This could, for whatever reason, also explain the extra bytes at the end perhaps.

You're right. I added the four = bytes and have the files playing correctly, thank you for your help regarding my problem on top of the investigation into the issue itself.

**Comment by Malvineous** [comment]
No worries, thanks for bringing the issue to my attention.  Even if supporting it is perhaps not the way to go, it's nonetheless a very interesting historical note.

Looking at the IMF data itself, there is much more redundancy than there is in later files, so it looks like they were produced by early versions of the tools as well.  Certain global registers that affect the whole OPL chip are written out on each channel, as if they didn't realise until later that the value was global and not specific to each channel.  I find little discoveries like that quite interesting :-)

I'll close this issue now since it looks like there will be no changes to AdPlug, but feel free to discuss further if needed.
