### ISSUE TITLE
Support updated RAD format

### ISSUE THREAD

**Issue by ghost** [adplug/adplug#66]
[Reality Adlib Tracker 2](http://www.3eality.com/productions/reality-adlib-tracker) was released a couple months ago with an updated file format.

C++ source for a player and example tracks are included and [it seems fairly well documented](http://www.3eality.com/productions/reality-adlib-tracker/docs) (ctrl+f "coding notes").

**Comment by devinacker** [comment]
I've actually made a branch of AdPlug a few months ago that added the RAD2 replayer, which I also modified to also support the original RAD format (instead of having them get converted to the generic Protracker-like format like they are currently).

I didn't release it at first because the replay code that came with the tracker didn't seem to actually specify any kind of license, and I don't remember if I ever contacted Reality about it (or if they ever added a license in the meanwhile...) But if that gets cleared up I can go ahead and open a PR, since it's basically already finished.

**Comment by AliceLR** [comment]
I contacted Reality a few days ago about their license and SHAYDE replied: "All source code in the RAD package is public domain."

**Comment by devinacker** [comment]
Excellent, I can try to get a PR ready soon then.
