### ISSUE TITLE
Somehow tie AdPlug in to Wine

### ISSUE THREAD

**Issue by Lantizia** [adplug/adplug#72]
Hey,

This is a long shot but I've been talking at length with the DOSBox/MAME guys on IRC and reading up on VOGONS posts to try and get a handle on what is/isn't possible.

Essentially I love the original Transport Tycoon Deluxe game (OpenTTD is great, just adds too much for my liking) and I mostly played the DOS version as a child on a mid 90's PC on a Sound Blaster VIBRA16.  But because it was the CT2260 model, my ears like the sound of OPL2 rather than OPL3 :)

Fast forward to today and I'm playing the Windows version of the game via Wine on my Linux desktop.  Works great, even applied a couple of minor patches from TTDPatch to get better resolution and mouse wheel support.  When it comes to the music it offers these options...

![image](https://user-images.githubusercontent.com/10448369/50730579-66b58380-1148-11e9-90bb-17b0919bf3a4.png)

So I installed both FluidSynth and the OPL3 SoundFont (both in the Ubuntu archives, no fussing around) and I pick the "FM Synth/SoundBlaster" option (as above) - Wine passes along the games request to play MIDI and everything works just fine... but to my ears the music only about 90% of what I remember from those days... and I can very easily compare against recordings someone took with OPL2 here... https://www.transporttycoon.net/music?recording=2&id=24

From what I've been able to determine I think that "FM Synth/SoundBlaster" option was meant to talk MIDI to the system (supposed to be Windows) and the system would have a driver installed to turn that MIDI into OPL2 FM sweet synthesised noise - but these kinds of drivers just aren't what Wine is meant to be used with.

From what I can tell Wine works with FluidSynth and Timidity just fine, would there be anyway to get AdPlug/AdPlay to receive these MIDI instructions instead and spit out the music (on a normal modern sound card, no OPL2 chip itsself) using WoodyOPL or DBOPL or other emulation? If Wine can't send to AdPlay/AdPlug, then maybe have FluidSynth act as a passthrough to it perhaps?

Thanks for reading,
Long shot anyway.

**Comment by Malvineous** [comment]
I'm not sure that this would solve your problem.  While I have done something similar to this before (I wrote an XMMS2 MIDI plugin that can send notes to AdPlug, so you can play MIDIs with an OPL synth) the issue is that the patch bank used (the actual instruments, like a SoundFont but for OPL synths) is controlled entirely by the synth itself.  There's no standardised way to change the patch bank.

This means that even if you did get this to work, you'd be hearing the music using the instruments that AdPlug defines, which are no doubt different to those used by the original game.  If you wanted to achieve this, you would need:

1. A system-specific MIDI front-end, that listens for MIDI events on some interface, presumably ALSA.  Both Fluidsynth and Timidity provide this interface, and I presume it's what Wine looks for as well.
2. A method of passing a custom patch bank to AdPlug.
3. The original patch bank used.  This is likely part of the Windows OPL driver.

Only if you did all of this would you get the game to sound like it originally did under Windows, which, since it's MIDI and not OPL, is likely to still be different to the way it sounded under DOS.  Possibly, if the DOS version also used MIDI, you could extract its patch bank instead and use that, which would probably let you get as close as possible to the sound of the original DOS music.

Also, for the record, OPL3 is just an enhancement to the OPL2, so when an OPL3 is running in its default mode it sounds identical to an OPL2.  I think the Vibra range of cards [might have used CQM synthesis](https://www.vogonswiki.com/index.php/Audio) instead of Yamaha's OPL chip though, so perhaps this is what you're thinking of?  I don't think AdPlug has a CQM synth.

**Comment by Lantizia** [comment]
Thanks for the detailed reply.

It got me thinking about the original sound card I used to play this on DOS with.  Opened up that old PC and realised it does actually have a chip that looks exactly like this one from Wikipedia...

![image](https://user-images.githubusercontent.com/10448369/50739045-2b5f9700-11d2-11e9-8c4a-a34a5a9ca95f.png)

Only mine says "9415 EAEC" and not "9416 EANC" - but that may just be a serial number.  So in short, it *does* seem to have OPL3 and whatever I'd read in the past about my CT2260 board only having OPL2 must have been wrong :S

But I can't help but feel like the music I hear here... https://www.transporttycoon.net/music?recording=2&id=24

Is what I remember.

Perhaps it's only possible to hear it this way in the DOS version.

**Comment by Malvineous** [comment]
MIDI is completely unrelated to OPL.  An OPL is just a way of producing sound.  It is possible to take MIDI instructions, and program the OPL synth to produce notes accordingly.  Generally when this is done, the programmer wants to make the best possible sound to make the MIDI sound as good as possible.  This means that if an OPL3 is available then all its advanced features will be used, but if not, then just the base OPL2 functions will be used.

This means MIDI will often sound different on OPL2 vs OPL3, precisely because OPL3 contains some enhancements which are used by many MIDI players.  Remember MIDI is just a list of notes, the actual sound of those notes is left up to the player to handle.

This is also why different MIDI players will sound different, even on the same OPL chip.  Each player includes a set of patches, which indicate how the OPL chip should be programmed for each instrument.  A piano with one patch set is going to sound different to a piano with another patch set, just like a piano sounds different on a modern machine if you change the SoundFont.

When you are using your OPL3 SoundFont there are two issues.  The major one is which patch set was used to create it?  If it was the same patch set as the game used then it should sound quite similar, but if it was a patch set from a different MIDI player then many of the instruments will sound different.  This is no doubt why the OPL2 SoundFont you found was also quite different to what you were after, because it was made with the instruments found in yet another patch bank.

The other issue is that a SoundFont is simply a recording of the instrument.  The OPL synthesises it in realtime and can have parameters of the instrument changed during playback to create effects that are part of some instruments.  This cannot generally be replicated in a static recording like you'd find in a SoundFont, so it will never sound exactly the same as the original, depending on how sophisticated the original player was.

AdPlug can play MIDI files directly so if you want to at least find out what it would sound like, you can try extracting the MIDI files from the game and playing them that way.  It won't sound the same as the DOS game either (unless by some amazing coincidence AdPlug and the game are using the same patch bank) but it will at least give you an idea of what it sounds like through a different OPL-based MIDI player.
